### PR TITLE
Fix MSWin32 test failures

### PR DESCRIPTION
**Pull request by rivy**
fix MSWin32 test errors with late path canonicalization
- alternative fix for PR/issue [GH#12](https://github.com/Getty/p5-dist-zilla-plugin-run/pull/12)
- includes PR/issue ~~[GH#14](https://github.com/Getty/p5-dist-zilla-plugin-run/pull/14)~~ [GH#16](https://github.com/Getty/p5-dist-zilla-plugin-run/pull/16) (for testing purposes)

... see [GH#12](https://github.com/Getty/p5-dist-zilla-plugin-run/pull/12) for further discussion about the proposed fix

### CODE REVIEW

**Comment by rivy** [comment]
I rebased the fix onto the improved CI code (see [PR#16](https://github.com/Getty/p5-dist-zilla-plugin-run/pull/16)).

**Comment by rivy** [comment]
@Getty , @karenetheridge ... checking back in; any movement on this PR ?

**Comment by karenetheridge** [comment]
I think this issue is fixed now, with the 0.045 release. Please re-test!

**Comment by xenu** [comment]
It still fails:
```
#   Failed test 'logged execution'
#   at t/10_build_phase.t line 80.
#                   '[Run::AfterBuild] executing: "C:\Strawberry\perl\bin\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build\script\no_trial.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build"'
#     doesn't match '(?^:\[Run::AfterBuild\] executing: .+ C\:\\Users\\xenu\\\.cpanm\\work\\1536190831\.7620\\Dist\-Zilla\-Plugin\-Run\-0\.047\\tmp\\qavnVsh_zt\\build\\script\\no_trial\.pl .+)'
# got log messages: [
#   '[Run::BeforeBuild] executing: "C:\\Strawberry\\perl\\bin\\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/source\\script\\before_build.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/source"',
#   '[Run::BeforeBuild] command executed successfully',
#   '[DZ] beginning to build DZT-Sample',
#   '[GatherDir] considering .',
#   '[GatherDir] considering BEFORE_BUILD.txt',
#   '[GatherDir] considering dist.ini',
#   '[GatherDir] considering lib',
#   '[GatherDir] considering lib/Foo.pm',
#   '[GatherDir] considering script',
#   '[GatherDir] considering script/after_build.pl',
#   '[GatherDir] considering script/before_build.pl',
#   '[GatherDir] considering script/no_trial.pl',
#   '[GatherDir] adding file BEFORE_BUILD.txt',
#   '[GatherDir] adding file dist.ini',
#   '[GatherDir] adding file lib/Foo.pm',
#   '[GatherDir] adding file script/after_build.pl',
#   '[GatherDir] adding file script/before_build.pl',
#   '[GatherDir] adding file script/no_trial.pl',
#   '[DZ] writing DZT-Sample in C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build',
#   '[Run::AfterBuild] executing: "C:\\Strawberry\\perl\\bin\\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build\\script\\after_build.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build"',
#   '[Run::AfterBuild] command executed successfully',
#   '[Run::AfterBuild] executing: "C:\\Strawberry\\perl\\bin\\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build\\script\\no_trial.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/qavnVsh_zt/build"',
#   '[Run::AfterBuild] command executed successfully'
# ]
# got log messages: [
#   '[Run::BeforeBuild] executing: "C:\\Strawberry\\perl\\bin\\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/UIVsNwHYxY/source\\script\\before_build.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/UIVsNwHYxY/source"',
#   '[Run::BeforeBuild] command executed successfully',
#   '[DZ] beginning to build DZT-Sample',
#   '[GatherDir] considering .',
#   '[GatherDir] considering BEFORE_BUILD.txt',
#   '[GatherDir] considering dist.ini',
#   '[GatherDir] considering lib',
#   '[GatherDir] considering lib/Foo.pm',
#   '[GatherDir] considering script',
#   '[GatherDir] considering script/after_build.pl',
#   '[GatherDir] considering script/before_build.pl',
#   '[GatherDir] considering script/no_trial.pl',
#   '[GatherDir] adding file BEFORE_BUILD.txt',
#   '[GatherDir] adding file dist.ini',
#   '[GatherDir] adding file lib/Foo.pm',
#   '[GatherDir] adding file script/after_build.pl',
#   '[GatherDir] adding file script/before_build.pl',
#   '[GatherDir] adding file script/no_trial.pl',
#   '[DZ] writing DZT-Sample in C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/UIVsNwHYxY/build',
#   '[Run::AfterBuild] executing: "C:\\Strawberry\\perl\\bin\\perl.exe" C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/UIVsNwHYxY/build\\script\\after_build.pl "C:/Users/xenu/.cpanm/work/1536190831.7620/Dist-Zilla-Plugin-Run-0.047/tmp/UIVsNwHYxY/build"',
#   '[Run::AfterBuild] command executed successfully',
#   '[Run::AfterBuild] not executing, because trial: "%x" %d%pscript%pno_trial.pl "%s"'
# ]
# Looks like you failed 1 test of 12.
t/10_build_phase.t ....... 
```

**Comment by xenu** [comment]
I have tried reverting `2eda638872adaae2d19bf19afc22aaece1b639da` and mergin this PR locally and it made test pass on my machine.

**Comment by rivy** [comment]
@Getty , @karenetheridge ... still broken.

**Comment by karenetheridge** [comment]
thanks for the nudge, @xenu! Hopefully this is at last fixed with 0.048.

**Comment by rivy** [comment]
I would have been happy to re-work the PR to your specs if you'd asked.

But, anyway, it does finally build/test without errors on an updated AppVeyor (at least back to perl v5.14; see https://ci.appveyor.com/project/rivy/perl-dist-zilla-plugin-run/builds/22253144) and Travis (see https://travis-ci.org/rivy/perl.dist-zilla-plugin-run/builds/491144344) CIs.

**Pull request closed without merging**
